import { Conversation } from "./types"

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: "visitor-4a8c",
    customerName: "Visitor 4a8c",
    customerEmail: "visitor-4a8c@anonymous.io",
    customerAvatarBg: "bg-orange-500",
    subjectSnippet: "Go to acme.example/login and click Forgot...",
    status: "open",
    lastActivity: "5m",
    assignedTo: "Super friendly Agent",
    tag: "Agent",
    messages: [
      {
        id: "m-4a8c-1",
        sender: "ai",
        senderName: "Super friendly Agent",
        text: "Hello from this super friendly agent 😊",
        timestamp: "Greeting",
      },
      {
        id: "m-4a8c-2",
        sender: "customer",
        senderName: "Visitor 4a8c",
        text: "How do I reset my password?",
        timestamp: "6 minutes ago",
      },
      {
        id: "m-4a8c-3",
        sender: "ai",
        senderName: "Super friendly Agent",
        text: "Go to acme.example/login and click Forgot password. Enter the email address you used to sign up, then open the reset email and click its link.\n\nThe email arrives within 5 minutes—check spam if needed. The link is valid for 1 hour, and your new password must be at least 10 characters.",
        timestamp: "6 minutes ago",
        source: "account-help.md",
      },
    ],
    copilot: {
      summary: "Visitor requested password reset instructions. Grounded via account-help.md knowledge base document.",
      linkedSource: {
        type: "knowledge_base",
        label: "account-help.md (0.70 match)",
        url: "#",
      },
      draftReply: {
        text: "Let me know if you received the password reset email or if you need an administrator to trigger a manual link.",
        sourcesCount: 1,
      },
      followUps: [
        { id: "f-1", label: "Check account activation status", completed: false },
      ],
      contextQueryLog: "account-help.md (0.70 score) >",
    },
  },
  {
    id: "visitor-305a",
    customerName: "Visitor 305a",
    customerEmail: "visitor-305a@anonymous.io",
    customerAvatarBg: "bg-blue-600",
    subjectSnippet: "Can I talk to a real person?",
    status: "open",
    lastActivity: "5m",
    tag: "Waiting",
    messages: [
      {
        id: "m-305a-1",
        sender: "customer",
        senderName: "Visitor 305a",
        text: "Can I talk to a real person?",
        timestamp: "5m",
      },
    ],
    copilot: {
      summary: "Visitor requested immediate human handoff.",
      linkedSource: {
        type: "knowledge_base",
        label: "operator-handoff-rules.md",
        url: "#",
      },
      draftReply: {
        text: "Hi there, I'm taking over from the AI assistant now. How can I assist you with your account today?",
        sourcesCount: 1,
      },
      followUps: [],
    },
  },
  {
    id: "visitor-2634",
    customerName: "Visitor 2634",
    customerEmail: "visitor-2634@anonymous.io",
    customerAvatarBg: "bg-amber-500",
    subjectSnippet: "Do you integrate with Salesforce?",
    status: "open",
    lastActivity: "5m",
    tag: "Waiting",
    messages: [
      {
        id: "m-2634-1",
        sender: "customer",
        senderName: "Visitor 2634",
        text: "Do you integrate with Salesforce?",
        timestamp: "5m",
      },
    ],
    copilot: {
      summary: "The knowledge base doesn't cover custom Salesforce bidirectional sync for Enterprise.",
      linkedSource: {
        type: "knowledge_base",
        label: "integrations-directory.md",
        url: "#",
      },
      draftReply: {
        text: "Yes, we integrate with Salesforce via OAuth2 AppExchange package or via our webhook sync engine.",
        sourcesCount: 1,
      },
      followUps: [],
    },
  },
  {
    id: "visitor-8bab",
    customerName: "Visitor 8bab",
    customerEmail: "visitor-8bab@anonymous.io",
    customerAvatarBg: "bg-orange-600",
    subjectSnippet: "Can I talk to a real person?",
    status: "open",
    lastActivity: "6m",
    tag: "Waiting",
    messages: [
      {
        id: "m-8bab-1",
        sender: "customer",
        senderName: "Visitor 8bab",
        text: "Can I talk to a real person?",
        timestamp: "6m",
      },
    ],
    copilot: {
      summary: "Visitor asked for a person. Escalated to operator queue.",
      linkedSource: {
        type: "knowledge_base",
        label: "operator-handoff-rules.md",
        url: "#",
      },
      draftReply: {
        text: "Hello! I am on the support team, happy to jump in and help. What questions do you have?",
        sourcesCount: 1,
      },
      followUps: [],
    },
  },
  {
    id: "visitor-7440",
    customerName: "Visitor 7440",
    customerEmail: "visitor-7440@anonymous.io",
    customerAvatarBg: "bg-sky-600",
    subjectSnippet: "Do you integrate with Salesforce?",
    status: "open",
    lastActivity: "6m",
    tag: "Waiting",
    messages: [
      {
        id: "m-7440-1",
        sender: "customer",
        senderName: "Visitor 7440",
        text: "Do you integrate with Salesforce?",
        timestamp: "6m",
      },
    ],
    copilot: {
      summary: "Knowledge base doesn't cover Salesforce Enterprise edition specific connectors.",
      linkedSource: {
        type: "knowledge_base",
        label: "integrations-directory.md",
        url: "#",
      },
      draftReply: {
        text: "We support Salesforce out of the box with our Enterprise tier. I can send you the documentation link.",
        sourcesCount: 1,
      },
      followUps: [],
    },
  },
  {
    id: "visitor-161d",
    customerName: "Visitor 161d",
    customerEmail: "visitor-161d@anonymous.io",
    customerAvatarBg: "bg-teal-600",
    subjectSnippet: "Is there a mobile app?",
    status: "open",
    lastActivity: "6m",
    tag: "Waiting",
    messages: [
      {
        id: "m-161d-1",
        sender: "customer",
        senderName: "Visitor 161d",
        text: "Is there a mobile app?",
        timestamp: "6m",
      },
    ],
    copilot: {
      summary: "Visitor asked about mobile app availability. iOS and Android apps are in private beta.",
      linkedSource: {
        type: "knowledge_base",
        label: "roadmap-mobile.md",
        url: "#",
      },
      draftReply: {
        text: "Yes, our iOS TestFlight is available now and Android APK can be requested from the dashboard.",
        sourcesCount: 1,
      },
      followUps: [],
    },
  },
  {
    id: "visitor-0ae2",
    customerName: "Visitor 0ae2",
    customerEmail: "visitor-0ae2@anonymous.io",
    customerAvatarBg: "bg-indigo-600",
    subjectSnippet: "Do you offer phone support?",
    status: "open",
    lastActivity: "6m",
    tag: "Waiting",
    messages: [
      {
        id: "m-0ae2-1",
        sender: "customer",
        senderName: "Visitor 0ae2",
        text: "Do you offer phone support?",
        timestamp: "6m",
      },
    ],
    copilot: {
      summary: "Visitor asked for phone support. Available on Enterprise tier with dedicated CSM.",
      linkedSource: {
        type: "knowledge_base",
        label: "plans-and-support-tiers.md",
        url: "#",
      },
      draftReply: {
        text: "Phone support is included with our Enterprise plans. You can schedule a call directly with our team here.",
        sourcesCount: 1,
      },
      followUps: [],
    },
  },
  {
    id: "visitor-cf46",
    customerName: "Visitor cf46",
    customerEmail: "visitor-cf46@anonymous.io",
    customerAvatarBg: "bg-cyan-600",
    subjectSnippet: "Sorry, returns are eligible for a full refund...",
    status: "open",
    lastActivity: "6m",
    tag: "Agent",
    messages: [
      {
        id: "m-cf46-1",
        sender: "customer",
        senderName: "Visitor cf46",
        text: "Can I return an item after 20 days?",
        timestamp: "7m",
      },
      {
        id: "m-cf46-2",
        sender: "ai",
        senderName: "Super friendly Agent",
        text: "Sorry, returns are eligible for a full refund within 30 days of delivery. Since you are within 20 days, you are fully covered!",
        timestamp: "6m",
        source: "refund-policy.pdf",
      },
    ],
    copilot: {
      summary: "Handled autonomously by agent via refund-policy.pdf.",
      linkedSource: {
        type: "knowledge_base",
        label: "refund-policy.pdf (0.84 match)",
        url: "#",
      },
      draftReply: {
        text: "Do you need a printable return shipping label?",
        sourcesCount: 1,
      },
      followUps: [],
    },
  },
  {
    id: "visitor-a32a",
    customerName: "Visitor a32a",
    customerEmail: "visitor-a32a@anonymous.io",
    customerAvatarBg: "bg-emerald-600",
    subjectSnippet: "Yes, we ship to Canada. Delivery typically...",
    status: "open",
    lastActivity: "6m",
    tag: "Agent",
    messages: [
      {
        id: "m-a32a-1",
        sender: "customer",
        senderName: "Visitor a32a",
        text: "Do you ship to Canada?",
        timestamp: "7m",
      },
      {
        id: "m-a32a-2",
        sender: "ai",
        senderName: "Super friendly Agent",
        text: "Yes, we ship to Canada. Delivery typically takes 3 to 5 business days with tracking included.",
        timestamp: "6m",
        source: "shipping-zones.md",
      },
    ],
    copilot: {
      summary: "Answered by agent via shipping-zones.md (0.91 confidence score).",
      linkedSource: {
        type: "knowledge_base",
        label: "shipping-zones.md (0.91 match)",
        url: "#",
      },
      draftReply: {
        text: "Let me know if you would like me to check the exact shipping rate for your postal code.",
        sourcesCount: 1,
      },
      followUps: [],
    },
  },
]
